apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodefrontend
  name: nodefrontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodefrontend
  type: LoadBalancer
status:
  loadBalancer: {}