apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodebackend
  name: nodebackend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: nodebackend
  type: ClusterIP