apiVersion: v1
kind: Service
metadata:
  namespace: react-namespace
  labels:
    app: reactui
  name: reactui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reactui
  type: LoadBalancer